title: iOS Font Sizes
email: 
author: zacwest
description: >-
  Preferred font sizes on iOS devices
baseurl: ""
url: ""

twitter:
  username: zacwest
  card: summary

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE